import type { Metadata, Viewport } from "next";
import { WildWorld, CondeSans } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Darrybook - ",
  description: "Generated by create next app",
  
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" data-google-analytics-opt-out="">
      <body>{children}</body>
    </html>
  );
}
